spring:
  application:
    name: custom-exceptions-validation

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: user
    password: 1234

server:
  port: 9000